services:
  library_back_service:
    container_name: 'library_back'
    image: 'library_image'
    build: 
      context: . 
    ports:
      - "8888:8000"
    networks:
      - my_network
    env_file:
      - .env

  library_db_service:
    container_name: 'library_db'
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "8432:5432"
    volumes:
      - pg-library-data:/var/lib/postgresql/data
    networks:
      - my_network

  library_cache_service:
    container_name: 'library_cache'
    image: redis:7.4
    ports:
      - "7379:6379"
    networks:
      - my_network

volumes:
  pg-library-data:

networks:
  my_network:
    external: true
