"""add cascade deleting to book and borrow tables

Revision ID: ecb636a974b8
Revises: 1ff82ca761ef
Create Date: 2024-12-13 21:25:40.153045

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "ecb636a974b8"
down_revision: Union[str, None] = "1ff82ca761ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("books_author_id_fkey", "books", type_="foreignkey")
    op.create_foreign_key(
        None, "books", "authors", ["author_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("borrows_book_id_fkey", "borrows", type_="foreignkey")
    op.create_foreign_key(
        None, "borrows", "books", ["book_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "borrows", type_="foreignkey")
    op.create_foreign_key(
        "borrows_book_id_fkey", "borrows", "books", ["book_id"], ["id"]
    )
    op.drop_constraint(None, "books", type_="foreignkey")
    op.create_foreign_key(
        "books_author_id_fkey", "books", "authors", ["author_id"], ["id"]
    )
    # ### end Alembic commands ###
