"""fix: remove extra(wrong) row from borrow table

Revision ID: 7442e4fbbd4e
Revises: b6d68f616d88
Create Date: 2024-12-09 21:00:11.994515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7442e4fbbd4e'
down_revision: Union[str, None] = 'b6d68f616d88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('borrows', 'available_copies')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrows', sa.Column('available_copies', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
